#!/bin/bash
#		Copyright (C) 2015  Nhoya.
#
#   gensum is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>

shr(){
	short=$(curl -s -L "http://z0r.it/yourls-api.php?signature=4e4b657a91&action=shorturl&keyword=$2&format=simply&url=$1")
        echo $short
        echo "$short" |xclip -selection clipboard
	}

regex='(https?|ftp|file)://[-A-Za-z0-9\+&@#/%?=~_|!:,.;]*\.[-A-Za-z0-9\+&@#/%=~_|():?]+'
url=(http://$1)

if [[ $1 =~ $regex ]];then
	shr $1 $2
else
if [[ $url =~ $regex ]];then
	shr $1 $2
else
	echo "Enter a valid url
fi
fi

