#!/bin/bash
#		Copyright (C) 2015  Nhoya.
#
#   gensum is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>

#text clours
readonly RED="\033[01;31m"
readonly GREEN="\033[01;32m"
readonly BLUE="\033[01;34m"
readonly YELLOW="\033[00;33m"
readonly BOLD="\033[01m"
readonly FINE="\033[0m"

regex='(https?|ftp|file)://[-A-Za-z0-9\+&@#/%?=~_|!:,.;]*\.[-A-Za-z0-9\+&@#/%=~_|():?]+'
url=(http://$1)
mode=-s
apikey=4e4b657a91
#upload function (long -> short)
shr(){
	short=$(curl $mode -L "http://z0r.it/yourls-api.php?signature=$apikey&action=shorturl&tile=uploaded_with_z0r_script&keyword=$2&format=simply&url=$1")
        echo $short
        echo "$short" |xclip -selection clipboard
	}
#expand function (short -> long)
expand(){
	avi=$(echo $@ |awk -F '/' '{print$NF}')
	exp=$(curl $mode -L  "http://z0r.it/yourls-api.php?signature=$apikey&action=expand&format=simply&shorturl=$avi")
	echo $exp
	echo "$exp" |xclip -selection clipboard
	}
#help screen
help(){
	echo -e "$YELLOW$BOLD$0$FINE, faster uploader for z0r.it shortner. Based on YOURL API"
	echo "Copyright(C) 2015 Nhoya"
        echo ""
        echo -e $BOLD"  Usage: $0 [long_URL] [custom_name]"$FINE
	echo  "	keep empty custom_name field for normal URL format"
	echo ""
	echo -e $GREEN"======================================================================================"$FINE
	echo " Available Options:"
	echo "		-e <short_URL>				expand URL (short -> long)"
	echo "		-h 					display this page"
	echo -e $GREEN"======================================================================================"$FINE

	}
#control over argument
is_url(){
if [[ $1 =~ $regex ]];then
	shr $1 $2
else
if [[ $url =~ $regex ]];then
	shr $1 $2
else
	echo -e  $RED"Enter a valid url"$FINE
fi
fi
}
#option parser
opsparser(){
while getopts ":he:" opt; do
		case "$opt" in
		h)	help
		exit 0
		;;
		e)      expand $@
		exit 0
		;;
		\?) 	echo -e $RED"enter a valid option, use -h for help"$FINE
		exit 0
		;;
		esac
done
}

opsparser $@
is_url $1 $2
